# Statistics With R Assignment 1

### 1. Create vectors d and h, then multiply element-wise

In [15]:
d <- c(4, 5, 6)
h <- c(2, 3, 4)
d * h

[1]  8 15 24

### 2. Sum vector k containing an NA value

In [16]:
k <- c(3, 8, NA, 9)
sum(k, na.rm = TRUE)

[1] 20

### 3. Create a matrix of order 2 by 2 having all numbers as 1.

In [17]:
m1 <- matrix(1, nrow = 2, ncol = 2)
m1

     [,1] [,2]
[1,] 1    1
[2,] 1    1

### 4. Say a vector w is having numbers 1, 2, 3, 4, 5, 6. Create a 2 by 3 matrix using this vector w.

In [18]:
w <- c(1, 2, 3, 4, 5, 6)
matrix_w <- matrix(w, nrow = 2, ncol = 3)
matrix_w

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

### 5. Say a vector q is having numbers from 1 to 6. Create a matrix of the order 2 by 3.

In [19]:
q <- 1:6
matrix_q <- matrix(q, nrow = 2, ncol = 3)
matrix_q

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

### 6. Say names of students are stored in vector names (names were Alberich, John, Steve, Chris). Their midterm marks are stored in vector midterm (87, 89, 93, 95 respectively). Their final marks are stored in vector final (92, 94, 95, 98 respectively). Create a data frame name result keeping all three vectors in it.

In [10]:
# 6. Create vectors and make the dataframe 'result'
names <- c("Alberich", "John", "Steve", "Chris")
midterm <- c(87, 89, 93, 95)
final <- c(92, 94, 95, 98)
result <- data.frame(names, midterm, final)
result

  names    midterm final
1 Alberich 87      92
2 John     89      94
3 Steve    93      95
4 Chris    95      98

### 7. Access second column (i) by the number of column (ii) by name of the column (iii) by $ sign.

In [11]:
# 7. Access second column (midterm):
# (i) by the number of column
col_num <- result[, 2]
print(col_num)

# (ii) by name of the column
col_name <- result[, "midterm"]
print(col_name)

# (iii) by $ sign
col_dollar <- result$midterm
print(col_dollar)

[1] 87 89 93 95
[1] 87 89 93 95
[1] 87 89 93 95

### 8. Merge files merge1 and merge2 and give name tests.

In [16]:
# Define datasets merge1 and merge2
merge1 <- data.frame(names = c("Alberich", "John", "Steve", "Chris"), class = c("A", "B", "A", "B"))
merge2 <- data.frame(names = c("Alberich", "John", "Steve", "Chris"), age = c(20, 21, 22, 20))

# Merge files merge1 and merge2 and give name tests
tests <- merge(merge1, merge2, by = "names")
tests

  names    class age
1 Alberich A     20
2 Chris    B     20
3 John     B     21
4 Steve    A     22

### 9. Save the merged data set tests at your desktop.

In [1]:
# Define merge1 and merge2 using the names vector created earlier
merge1 <- data.frame(names = c("Alberich", "John", "Steve", "Chris"), class = c("A", "B", "A", "B"))
merge2 <- data.frame(names = c("Alberich", "John", "Steve", "Chris"), age = c(20, 21, 22, 20))

# Merge files merge1 and merge2
tests <- merge(merge1, merge2, by = "names")
tests

  names    class age
1 Alberich A     20
2 Chris    B     20
3 John     B     21
4 Steve    A     22

In [3]:
# Create Desktop directory if it doesn't exist, then save the file
dir.create("~/Desktop", showWarnings = FALSE, recursive = TRUE)
write.csv(tests, file = "~/Desktop/tests.csv", row.names = FALSE)

# Also save a copy in the current directory for easy access in Colab
write.csv(tests, file = "tests.csv", row.names = FALSE)

### 10. Use all the methods for adding datasets.

In [4]:
# 1. Horizontal join by key/ID (Merge)
merged_data <- merge(merge1, merge2, by = "names")
merged_data

  names    class age
1 Alberich A     20
2 Chris    B     20
3 John     B     21
4 Steve    A     22

In [5]:
# 2. Binding by columns (Side-by-side, requires same number of rows)
cbind_data <- cbind(merge1, merge2)
cbind_data

  names    class names    age
1 Alberich A     Alberich 20
2 John     B     John     21
3 Steve    A     Steve    22
4 Chris    B     Chris    20

In [7]:
# 3. Binding by rows (Stacked, requires same column names and structures)
# Create a new dataset of additional students with matching columns to merge1
new_students <- data.frame(names = c("Emma", "Liam"), class = c("A", "B"))

rbind_data <- rbind(merge1, new_students)
rbind_data

  names    class
1 Alberich A
2 John     B
3 Steve    A
4 Chris    B
5 Emma     A
6 Liam     B

### 11. Crate list from the above created vectors.

In [14]:
# 11. Create list from the above created vectors.
names <- c("Alberich", "John", "Steve", "Chris")
midterm <- c(87, 89, 93, 95)
final <- c(92, 94, 95, 98)

student_list <- list(
  student_names = names,
  midterm_scores = midterm,
  final_scores = final
)
student_list

$student_names
[1] "Alberich" "John"     "Steve"    "Chris"

$midterm_scores
[1] 87 89 93 95

$final_scores
[1] 92 94 95 98

### 12. Convert any vector in factor vector.

In [15]:
# 12. Convert any vector in factor vector.
names <- c("Alberich", "John", "Steve", "Chris")
names_factor <- factor(names)
names_factor

[1] Alberich John     Steve    Chris
Levels: Alberich Chris John Steve